import type { CSSProperties } from "react";
import { Reveal } from "./Reveal";
import { motion, useReducedMotion } from "framer-motion";

// Each case study carries its own signature hue from the palette.
const accents = [
  "var(--accent)",
  "var(--accent-2)",
  "var(--accent-3)",
  "var(--accent-5)",
  "var(--accent-4)",
  "var(--accent)",
];

type Project = {
  index: string;
  category: string;
  title: string;
  bullets: string[];
  tags: string[];
  href?: string;
};

const projects: Project[] = [
  {
    index: "01",
    category: "Causal Deep Learning",
    title: "VAE Variants for Causal Effect Estimation",
    bullets: [
      "Extended the CEVAE deep latent-variable model (NeurIPS 2017) to test whether advanced VAE architectures improve causal effect estimation under unmeasured confounders, implementing four variants in PyTorch: Correlated-VAE, Beta-VAE, Hierarchical VAE, and VQ-VAE.",
      "Built an end-to-end evaluation pipeline with grid search hyperparameter tuning, Adamax optimization, early stopping, and parallel experiment execution, benchmarking all models on 3 real-world datasets (IHDP, JOBS, TWINS) and synthetic data across 4 causal metrics (ATE, ATT, PEHE, policy risk).",
      "Achieved best PEHE of 1.47 ± 0.18 and ATE error of 1.26 ± 0.75 on the JOBS dataset, and showed that standard CEVAE matches more complex variants in accuracy, indicating its architecture has sufficient capacity for these causal inference tasks.",
    ],
    tags: ["PyTorch", "CEVAE", "Beta-VAE", "VQ-VAE", "Causal Inference"],
  },
  {
    index: "02",
    category: "Sports Analytics",
    title: "Soccer Analytics Dashboard",
    bullets: [
      "Integrated and cleaned 11 disparate soccer datasets totaling 3M+ records using Python and SQL, building an ETL workflow to resolve inconsistent keys, missing values, and duplicate entries across sources.",
      "Engineered performance metrics and season-level aggregations from raw match and player data, then designed an interactive Tableau dashboard with filters and drill-downs for exploring trends across teams, players, and seasons.",
      "Optimized performance with Tableau extracts and pre-aggregated views to keep the dashboard responsive on 3M+ rows, published on Tableau Public as a portfolio piece.",
    ],
    tags: ["SQL", "Python", "Tableau", "ETL", "Feature Engineering"],
  },
  {
    index: "03",
    category: "Causal Inference · LLMs",
    title: "Causal Analysis using Large Language Models",
    bullets: [
      "Built an LLM-based causal discovery pipeline that infers causal structure among 23 under-five child health variables (immunization, malnutrition, schooling, WASH) from a MICS-style household survey.",
      "Designed a batched prompting system where Claude/GPT-4o classifies variable pairs as CAUSES, CAUSED_BY, CORRELATED, CONFOUNDED, or INDEPENDENT with structured JSON output, then converts directed judgments into an adjacency matrix and causal graph.",
      "Benchmarked the LLM-inferred graph against two statistical causal discovery baselines, DECI and LinGAM, using edge overlap analysis and five centrality metrics (in/out-degree, betweenness, closeness, eigenvector) to quantify where domain knowledge and data-driven methods agree.",
      "Implemented core causal inference algorithms from scratch: path enumeration, collider detection, d-separation (with collider-descendant handling), backdoor path identification, minimal adjustment set search, and identifiability checks.",
      "Built a natural-language query engine where Claude parses questions like “What should I control for when studying schooling’s effect on malnutrition?” into structured operations executed deterministically against the graph, so answers are derived from formal logic, not generated by the LLM.",
      "Validated with a test suite covering parents, confounders, adjustment sets, colliders, d-separation, and identifiability queries.",
    ],
    tags: ["Claude", "GPT-4o", "NetworkX", "d-separation", "Causal Inference"],
  },
  {
    index: "04",
    category: "LLM Agents · Statistics",
    title: "Automated Statistical Discovery for Tabular Data",
    bullets: [
      "Built a Streamlit-based data exploration assistant that uses LangChain tool-calling to profile tabular datasets, suggest natural-language hypotheses, run user-approved cleaning steps, execute SciPy statistical tests, and generate reproducible Python analysis code with visualizations.",
    ],
    tags: ["LangChain", "Streamlit", "SciPy", "LLM Agents"],
  },
  {
    index: "05",
    category: "Time Series · Public Health",
    title: "TB Forecasting with ARIMA & POMP",
    bullets: [
      "Compared ARIMA and SEIRS-based POMP models for TB incidence prediction in R, applying ANOVA-based model evaluation and stochastic modeling with time-varying transmission parameters to improve forecasting accuracy and generate reproducible analytical reports.",
    ],
    tags: ["R", "ARIMA", "POMP", "SEIRS"],
  },
  {
    index: "06",
    category: "Applied ML · Fuzzy Logic",
    title: "Shark Tank India: Deal & Quality Prediction",
    bullets: [
      "Built an ANN model to predict whether Shark Tank India investors would make an offer to a startup, achieving an F1 score of 87.09% on an imbalanced dataset, outperforming SVM, Random Forest, KNN, and other classifiers.",
      "Designed a 22-rule Mamdani fuzzy logic system to classify deal quality (below average / average / good) based on startup revenue, valuation, and age, producing interpretable outputs founders can act on.",
      "Curated a custom dataset of 121 Shark Tank India pitches from public sources, engineering features like YoY revenue, equity ask, industry, and founder demographics through label encoding and imputation.",
      "Identified key pre-pitch predictors of investor offers — revenue, industry, ask amount, and equity percentage — isolating only features available before a deal is declared to avoid data leakage.",
      "Published and presented at ACM ICIMMI 2022.",
    ],
    tags: ["Python", "ANN", "Fuzzy Logic", "MATLAB", "EDA"],
  },
];

function ProjectRow({ p, i }: { p: Project; i: number }) {
  const reduce = useReducedMotion();
  const c = accents[i % accents.length];

  return (
    // Sticky stack (desktop): each card pins at the top with a higher z-index,
    // so the next project slides up and covers the previous one. On mobile it
    // falls back to normal flow (long bullet lists would overflow a viewport).
    <article
      style={{ zIndex: i + 1, "--c": c } as CSSProperties}
      className="group relative border-t border-rule bg-canvas md:sticky md:top-0 md:flex md:min-h-screen md:items-center md:overflow-hidden md:rounded-t-[2.25rem] md:border-t-0 md:shadow-[0_-26px_60px_-34px_rgba(0,0,0,0.4)]"
    >
      {/* Signature color accents for this case study */}
      <span
        aria-hidden
        className="absolute inset-x-0 top-0 h-1 md:rounded-t-[2.25rem]"
        style={{ background: "linear-gradient(90deg, var(--c), transparent 75%)" }}
      />
      <span
        aria-hidden
        className="pointer-events-none absolute -top-24 right-0 h-72 w-72 rounded-full opacity-50 blur-3xl"
        style={{ background: "color-mix(in oklab, var(--c) 22%, transparent)" }}
      />

      <div className="relative mx-auto grid w-full max-w-7xl gap-x-10 gap-y-7 px-6 py-14 md:grid-cols-12 md:px-10 md:py-16">

        {/* Left rail — big index, category, tags */}
        <div className="md:col-span-4 md:self-start lg:col-span-3">
          <Reveal y={28}>
            <span
              className="block font-serif text-[3.5rem] leading-none md:text-[4.5rem]"
              style={{ color: "color-mix(in oklab, var(--c) 70%, transparent)" }}
            >
              {p.index}
            </span>
            <p
              className="mt-4 font-mono text-[11px] uppercase tracking-[0.2em]"
              style={{ color: "var(--c)" }}
            >
              {p.category}
            </p>
            <ul className="mt-6 flex flex-wrap gap-2">
              {p.tags.map((t) => (
                <li
                  key={t}
                  className="rounded-full border px-3 py-1 font-mono text-[10.5px] tracking-wide text-ink-soft"
                  style={{
                    borderColor: "color-mix(in oklab, var(--c) 32%, transparent)",
                    background: "color-mix(in oklab, var(--c) 7%, transparent)",
                  }}
                >
                  {t}
                </li>
              ))}
            </ul>
          </Reveal>
        </div>

        {/* Right — title + detailed contributions */}
        <div className="md:col-span-8 lg:col-span-9">
          <Reveal y={28}>
            <h3 className="mb-8 font-serif text-[2rem] leading-[1.08] text-balance md:text-4xl lg:text-[2.75rem]">
              {p.title}
            </h3>
          </Reveal>

          {/* Staggered reveal as bullets enter the viewport */}
          <motion.ul
            className="space-y-5 border-l pl-7"
            style={{ borderColor: "color-mix(in oklab, var(--c) 35%, var(--rule))" }}
            initial={reduce ? false : "hidden"}
            whileInView="show"
            viewport={{ once: true, margin: "-80px" }}
            variants={{ show: { transition: { staggerChildren: 0.08 } } }}
          >
            {p.bullets.map((b, bi) => (
              <motion.li
                key={bi}
                variants={{
                  hidden: { opacity: 0, y: 18 },
                  show: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.16, 1, 0.3, 1] } },
                }}
                className="relative text-[15px] leading-[1.74] text-ink-soft"
              >
                <span
                  aria-hidden
                  className="absolute -left-[30px] top-[0.7em] h-[7px] w-[7px] rounded-full"
                  style={{ background: "var(--c)" }}
                />
                {b}
              </motion.li>
            ))}
          </motion.ul>

          {p.href && (
            <Reveal y={16} delay={reduce ? 0 : 0.08 * p.bullets.length}>
              <a
                href={p.href}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-9 inline-flex items-center gap-2 border-b border-ink/25 pb-px font-mono text-xs uppercase tracking-[0.18em] text-ink transition-colors hover:border-ink"
              >
                View Project
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M7 17L17 7" /><path d="M7 7h10v10" />
                </svg>
              </a>
            </Reveal>
          )}
        </div>
      </div>
    </article>
  );
}

export function Work() {
  const total = projects.length;

  return (
    <section id="work" className="relative bg-canvas">
      {/* Section header */}
      <div className="border-y border-rule bg-canvas-alt/60 px-6 py-20 md:px-10 md:py-28">
        <div className="max-w-7xl mx-auto">
          <Reveal className="flex flex-col gap-8 md:flex-row md:items-end md:justify-between">
            <div className="max-w-[44ch]">
              <h2 className="mb-5 text-[11px] uppercase tracking-[0.22em] text-accent">
                02 / Selected Work
              </h2>
              <p className="font-serif text-3xl leading-tight text-balance md:text-4xl">
                Translating complex datasets into models, dashboards, and decisions that actually
                ship.
              </p>
            </div>
            <p className="shrink-0 font-mono text-sm text-muted">
              {String(total).padStart(2, "0")} case studies
            </p>
          </Reveal>
        </div>
      </div>

      {/* Editorial project rows — sticky stack so each slides over the last */}
      <div className="relative">
        {projects.map((p, i) => (
          <ProjectRow key={p.title} p={p} i={i} />
        ))}
      </div>
    </section>
  );
}
